---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.4
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[aws_tools::ec2_ami_tools]
      - recipe[aws_tools::ec2_api_tools]
    attributes:
